virsh: Free stream when shutdown console
Otherwise connection of hypervisor driver will be leaked when
one shutdown the guest in console. e.g.

[root@localhost]# init 0
......
init: Re-executing /sbin/init
Halting system...
Power down.

error: Failed to disconnect from the hypervisor, 1 leaked reference(s)
(cherry picked from commit abfa97a2259e4b9cc8843b164e94c0e4aa26ec57)

Signed-off-by: Steve Hodgson <shodgson@solarflare.com>